### PR TITLE
Fix notebook repo clone

### PR DESCRIPTION
**Pull request by aeongdesu**
after updating notebook(#844), it errors during cloning repo process.

image

idk why but It fixed by adding `--depth=1` again.

@Rafacasari, could you update your kaggle notebook?

### CODE REVIEW

**Comment by aeongdesu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by aeongdesu** [comment]
image

**Comment by bennett-krubakar** [comment]
umm...is it working now? because I tried to run it with the change you have suggested but I can only assume some changes are being worked on as I am typing this and I just ran into a lot of errors.

image

image

**Comment by aeongdesu** [comment]
@bennett-krubakar yeah me either LMAO
haven't checked but i think kaggle is broken rn, let me keep test it
image

**Comment by bennett-krubakar** [comment]
The installation of dependencies and packages is working fine now. However, we are facing some issues with starting the server. These are the errors I got:

```
Traceback (most recent call last):
  File "/kaggle/working/voice-changer/server/MMVCServerSIO.py", line 153, in <module>
  5%|█▉                                     | 8.71M/181M [00:01<00:27, 6.49MB/s]    downloadWeight(voiceChangerParams)
  File "/kaggle/working/voice-changer/server/downloader/WeightDownloader.py", line 122, in downloadWeight
    with ThreadPoolExecutor() as pool:





  File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 649, in __exit__
  6%|██▍                                   | 5.50M/84.9M [00:01<00:16, 5.20MB/s]    self.shutdown(wait=True)
  File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 235, in shutdown
    t.join()
  File "/opt/conda/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/opt/conda/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
```

After I get this, my session just shuts down.

**Comment by aeongdesu** [comment]
@bennett-krubakar they blocked rvc thing, gg (even not using quick tunnel like ngrok, cloudflared!!!!)
btw, this pr is for fix cloning repo so I will open it again

**Comment by Rafacasari** [comment]
I'll investigate and update my notebook on Kaggle. It was working without any problem, so is kinda weird. Hope they didn't banned Voice Changer too.

**Comment by aeongdesu** [comment]
closing now, it was avoid bypass block thing.
it can reproduce by using `ngrok && sleep 10m`.
someone will found running voice changer hopefully \~v~

**Pull request closed without merging**
