### PR TITLE
bugfix: when run server with python3 MMVCServerSIO.py on linux, voice…

### PR DESCRIPTION
**Pull request by leeyeel**
…ChangerParams class will not be initialized and keeping None type

### CODE REVIEW

**Comment by filianfan1232** [comment]
> …ChangerParams class will not be initialized and keeping None type

how do i use someones script?

**Comment by w-okada** [comment]
Sorry for late response. And I have not yet understand why this is needed.
Please tell me when problem occurs without this modification.

**Comment by leeyeel** [comment]
[Run server](https://github.com/w-okada/voice-changer/blob/master/README_dev_en.md)

```
$ python3 MMVCServerSIO.py -p 18888 --https true \
    --content_vec_500 pretrain/checkpoint_best_legacy_500.pt  \
    --content_vec_500_onnx pretrain/content_vec_500.onnx \
    --content_vec_500_onnx_on true \
    --hubert_base pretrain/hubert_base.pt \
    --hubert_base_jp pretrain/rinna_hubert_base_jp.pt \
    --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt \
    --nsf_hifigan pretrain/nsf_hifigan/model \
    --crepe_onnx_full pretrain/crepe_onnx_full.onnx \
    --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx \
    --rmvpe pretrain/rmvpe.pt \
    --model_dir model_dir \
    --samples samples.json
```
This error typically occurs when I intentionally ignore a certain input parameter (that I won't use). Because no argument has been passed in, this parameter will remain as None in VoiceChangerParams. When the os.path.exists check is performed in the downloadWeight function, it will raise a TypeError due to this.

Of course, this is not considered a bug, but it might be better if there were an opportunity to be a bit lazy. Or at the very least, allow for some parameters to be optional.

**Comment by leeyeel** [comment]
> > …ChangerParams class will not be initialized and keeping None type
> 
> how do i use someones script?

If you're asking about how to run it on Linux, this will be very helpful to you.· [For Server Developer](https://github.com/w-okada/voice-changer/blob/master/README_dev_en.md)

**Comment by filianfan1232** [comment]
can someone explain to me how to use github. also how to use w-okada's voicechanger

**Comment by w-okada** [comment]
Thanks for your advice. That's true. However, I thought it might be better to set a default value there. Do you think we could improve it in that direction?

**Comment by leeyeel** [comment]
> Thanks for your advice. That's true. However, I thought it might be better to set a default value there. Do you think we could improve it in that direction?

Adding a default value can perfectly avoid issues caused by type errors. But to be frank, this could help most people except Chinese. This is because we have a strictly limited internet environment, so we always try to avoid unnecessary downloads. Personally, I certainly prefer having these options as optional settings instead of enforced ones. Of course,  that would be perfect if it can use the default value and allow me to download fewer files.

**Comment by w-okada** [comment]
Added default value for cli parameter.

**Pull request closed without merging**
